name: ptenv
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1d=h1de35cc_4
  - pip=20.0.2=py36_1
  - python=3.6.10=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=46.0.0=py36_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.9.0
    - appnope==0.1.0
    - args==0.1.0
    - arrow==0.15.5
    - astor==0.8.1
    - attrs==19.3.0
    - backcall==0.1.0
    - beautifulsoup4==4.9.0
    - binaryornot==0.4.4
    - bleach==3.1.4
    - blis==0.4.1
    - bottleneck==1.3.2
    - cachetools==4.0.0
    - catalogue==1.0.0
    - cffi==1.14.0
    - chardet==3.0.4
    - click==6.7
    - clint==0.5.1
    - cmake==3.17.2
    - cookiecutter==1.7.0
    - cycler==0.10.0
    - cymem==2.0.3
    - dataclasses==0.7
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - enum34==1.1.10
    - fastai==1.0.60
    - fastprogress==0.2.3
    - flake8==3.7.9
    - flask==1.1.2
    - flatbuffers==1.12
    - floyd-cli==0.11.17
    - future==0.18.2
    - gast==0.2.2
    - get==2019.4.13
    - google-auth==1.11.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.27.2
    - h5py==2.10.0
    - hydra-core==0.11.3
    - idna==2.9
    - importlib-metadata==1.6.0
    - ipykernel==5.2.0
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jedi==0.16.0
    - jinja2==2.11.1
    - jinja2-time==0.2.0
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.2
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - kaggle==1.5.6
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.2.0
    - markdown==3.2.1
    - markupsafe==1.1.1
    - marshmallow==2.21.0
    - matplotlib==3.2.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - mnn==1.0.0
    - murmurhash==1.0.2
    - mxnet==1.6.0
    - nbconvert==5.6.1
    - nbformat==5.0.5
    - notebook==6.0.3
    - numexpr==2.7.1
    - numpy==1.18.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - omegaconf==1.4.1
    - onnx==1.6.0
    - opencv-python==4.2.0.34
    - opt-einsum==3.2.0
    - packaging==20.3
    - pandas==1.0.2
    - pandocfilters==1.4.2
    - parso==0.6.2
    - pathlib2==2.3.5
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.0.0
    - plac==1.1.3
    - plaidml==0.7.0
    - plaidml-keras==0.7.0
    - post==2019.4.13
    - poyo==0.5.0
    - preshed==3.0.2
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - public==2019.4.13
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pycparser==2.20
    - pydot-ng==2.0.0
    - pyflakes==2.1.1
    - pygments==2.6.1
    - pynvx==1.0.0
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - python-graphviz==0.8.4
    - python-slugify==4.0.0
    - pytz==2019.3
    - pyyaml==5.3
    - pyzmq==19.0.0
    - qtconsole==4.7.2
    - qtpy==1.9.0
    - query-string==2019.4.13
    - raven==6.10.0
    - request==2019.4.13
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rsa==4.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - send2trash==1.5.0
    - six==1.14.0
    - sklearn==0.0
    - soupsieve==2.0
    - spacy==2.2.4
    - srsly==1.0.2
    - tabulate==0.8.7
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - text-unidecode==1.3
    - thinc==7.4.0
    - torch==1.4.0
    - torchsummary==1.5.1
    - torchvision==0.5.0
    - tornado==6.0.4
    - tqdm==4.43.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.2
    - urllib3==1.24.3
    - wasabi==0.6.0
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - werkzeug==1.0.0
    - whichcraft==0.6.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - zipp==3.1.0
prefix: /usr/local/anaconda3/envs/ptenv

